###########
# site.title

title:    'Beau Heubach'
subtitle: 'Pixel Pushing User Advocate'
collections:
  content:
    output: true

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
